export const programOptions = [
  { value: "Anthropology", label: "Anthropology" },
  { value: "Biology", label: "Biology" },
  { value: "Business Administration", label: "Business Administration" },
  { value: "Chemistry", label: "Chemistry" },
  { value: "Computer Science", label: "Computer Science" },
  { value: "Education", label: "Education" },
  { value: "Engineering", label: "Engineering" },
  { value: "English", label: "English" },
  { value: "Environmental Science", label: "Environmental Science" },
  { value: "Fine Arts", label: "Fine Arts" },
  { value: "Health Sciences", label: "Health Sciences" },
  { value: "History", label: "History" },
  { value: "International Relations", label: "International Relations" },
  { value: "Law", label: "Law" },
  { value: "Mathematics", label: "Mathematics" },
  { value: "Media Studies", label: "Media Studies" },
  { value: "Music", label: "Music" },
  { value: "Nursing", label: "Nursing" },
  { value: "Physics", label: "Physics" },
  { value: "Psychology", label: "Psychology" },
  { value: "Social Sciences", label: "Social Sciences" },
  { value: "Sociology", label: "Sociology" },
  { value: "Other", label: "Other" },
];
